# Generated by Django 4.1.7 on 2023-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("egradu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcomments",
            name="commented_document",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
